baseURL = 'https://funcsec.github.io/sv-issa.github.io/'
languageCode = 'en-US'
title = 'Silicon Valley ISSA Chapter'
theme = 'sv-issa-theme'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'About Us'
    weight = 20
  [[menus.main]]
    name = 'Board'
    pageRef = '/about/sv-issa-board'
    weight = 1
    parent = 'About Us'
  [[menus.main]]
    name = 'ISSA International'
    pageRef = '/about/issa-international'
    weight = 2
    parent = 'About Us'

  [[menus.main]]
    name = 'Meetings'
    weight = 30
  [[menus.main]]
    name = 'Upcoming Meeting'
    weight = 1
    parent = 'Meetings'
  [[menus.main]]
    name = 'Past Meetings'
    weight = 2
    pageRef = '/meetings'
    parent = 'Meetings'


  [[menus.main]]
    name = 'Career Center'
    weight = 40
  [[menus.main]]
    name = 'Jobs'
    weight = 1
    pageRef = '/jobs'
    parent = 'Career Center'
  [[menus.main]]
    name = 'Certifications'
    weight = 2
    pageRef = '/certifications'
    parent = 'Career Center'

  [[menus.main]]
    name = 'Social'
    weight = 50
  [[menus.main]]
    name = 'Linkedin'
    url = 'https://www.linkedin.com/groups/841137'
    weight = 1
    parent = 'Social'
  [[menus.main]]
    name = 'Slack'
    url = 'https://join.slack.com/t/sv-sf-issa/shared_invite/zt-2q26azbo0-WC_V5mKPF7JCqJXgRJO90Q'
    weight = 2
    parent = 'Social'

  [[menus.main]]
    name = 'Participate'
    weight = 70
  [[menus.main]]
    name = 'Become a Member'
    url = 'https://www.members.issa.org/page/join-now'
    weight = 1
    parent = 'Participate'

  [[menus.main]]
    name = 'Become a Speaker'
    url = 'https://docs.google.com/forms/d/e/1FAIpQLScqgYgVqdDO5JLsLLJLQixk93ZpI8DLZXxuyPUv8L_nRNRjxw/viewform'
    weight = 2
    parent = 'Participate'

  [[menus.main]]
    name = 'Sponsor Us'
    url = 'https://docs.google.com/forms/d/e/1FAIpQLScSo5s6jfVYE3Qkfw8CGz1jYHUTSaxSfoMhX7TopaXKnxOpCw/viewform'
    weight = 3
    parent = 'Participate'

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
